### ISSUE TITLE
Brutto Pfand Frontend

### ISSUE THREAD

**Issue by creating** [nerdissimo-de/woocommerce-pfand#1]
Hi, vielen Dank für Plugin. Läuft auch ansich super. Aber gibts ne Möglichkeit im Frontend den Preis brutto ausgeben zu lassen?

Habs in der class-woocommerce-pfand-public.php geändert.

`return $product_price . '<br /><small class="deposit_label">' .  sprintf( __( 'plus deposit of %s', $this->woocommerce_pfand ), wc_price( $dep_total * 1.19  ) ) . '</small>';`
Aus Zeile 98.

Wäre allerdings cool, wenn das ganze dann nicht fix drin stünde. Da bin ich aber noch nicht wirklich weiter gekommen.

**Comment by jessor** [comment]
Du kannst Steuerberechnung für den Pfand aktivieren.

Probier mal, ob Du damit weiterkommst:

 `$woocommerce->cart->add_fee( __( 'Deposit Total', $this->woocommerce_pfand ), $dep_total, true );`
statt
`$woocommerce->cart->add_fee( __( 'Deposit Total', $this->woocommerce_pfand ), $dep_total );`
in
https://github.com/nerdissimo-de/woocommerce-pfand/blob/master/public/class-woocommerce-pfand-public.php#L131.

**Comment by creating** [comment]
Hmm, aber bezieht sich dass nicht nur auf den Warenkorb? Dass sah eigentlich schon ganz gut aus. Ging halt wirklich nur um die archive, content, single, cart-Seiten. Und da wird das ganze über sprintf eingebunden.

**Comment by jessor** [comment]
Also suchst Du nur nach einem Weg, die 19 % bei Produkten im Loop nicht hardcoden zu müssen?

Dafür könntest Du Dir mal `WC_Tax::get_rates()` anschauen.

**Comment by creating** [comment]
Hey, hab ich, aber ich glaub da bin ich noch nicht fit genug. Aber schonmal Danke für die Prompte Hilfe.

**Comment by jessor** [comment]
Kein Problem. Da gibt es halt ganz verschiedene Anforderungen in dem Bereich, auch was Kompatibilität mit Plugins wie Woocommerce German Market oder Germanize angeht.
