### ISSUE TITLE
Price entry not possible

### ISSUE THREAD

**Issue by Lexxorian** [nerdissimo-de/woocommerce-pfand#2]
I installed the plugin (WP 4.6.1 and WooCommerce 2.6.7, PHP 5.6.27) but it is not possible  to entry a deposit value (price)
![zwischenablage01](https://cloud.githubusercontent.com/assets/23216152/19932669/35b3e4a6-a111-11e6-97fd-9ecc434bb8b2.jpg)

**Comment by jessor** [comment]
Hi @Lexxorian,

the name field is where you enter the price. Note also: use "." as the decimal separator, e.g. "0.08".

**Comment by Lexxorian** [comment]
Hello Daniel, 

 

thank you very much, that was it. The Name field was a little bit missleading for me. 

 

I have another question, the lone "Total deposit" is now shown at every product in the checkout, with 0,00 EUR. Is it possible to show this line only at product which has an entry in the deposit field >0 ?

 

Viele Grüße

Ivan Horvat

 

 

Gesendet: Mittwoch, 02. November 2016 um 15:38 Uhr
Von: "Daniel Kay" notifications@github.com
An: nerdissimo-de/woocommerce-pfand woocommerce-pfand@noreply.github.com
Cc: Lexxorian lexxorian@gmx.de, Mention mention@noreply.github.com
Betreff: Re: [nerdissimo-de/woocommerce-pfand] Price entry not possible (#2)

Hi @Lexxorian,

the name field is for the price. Note also: use "." as the decimal separator, e.g. "0.08".

**Comment by jessor** [comment]
That would be a bug, this is not supposed to happen. Could you provide an URL and login credentials via private mail, please?

**Comment by jessor** [comment]
That bug has been fixed with the commit f49a30f941.
