### ISSUE TITLE
API Support?

### ISSUE THREAD

**Issue by neilscudder** [nerdissimo-de/woocommerce-pfand#3]
Could you tell me please if the woocommerce API is supported? I am importing products and need to bring in a deposit for each one. Thank you for the excellent plugin.

**Comment by jessor** [comment]
Deposit is just a custom taxonomy, I think even the WP Importer should work.

See: https://github.com/nerdissimo-de/woocommerce-pfand/blob/master/admin/class-woocommerce-pfand-admin.php#L171

Cheers

**Comment by Zachhh17** [comment]
Question... I cannot get the importer to work with this. Any ideas?
