### ISSUE TITLE
Need to add VAT to the deposit

### ISSUE THREAD

**Issue by Vyffe** [nerdissimo-de/woocommerce-pfand#5]
Hi pfand makers,

Thanks for a great plugin. 

What would it take to add a VAT (tax) feature to the plugin? By Danish law VAT have to be added to a deposit.

/Simon

**Comment by jessor** [comment]
Hi Vyffe,

you can use the documented hooks to add your own calculations or contact us for a custom coded extension.

Cheers

**Comment by Vyffe** [comment]
I am not skilled with coding. 

But the deposit have to be included in the total sum before calculation the VAT for the invoice.

Is this possible with the current documented hooks?
